# Generated by Django 6.0.3 on 2026-03-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.DecimalField(decimal_places=5, max_digits=5),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='title',
            field=models.CharField(),
        ),
    ]
