# Generated by Django 6.0.4 on 2026-04-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0003_alter_productmodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
